name: Check configuration schema changes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'server/package.json'
  workflow_dispatch:

permissions:
  pull-requests: write
  repository-projects: write

jobs:
  check-settings:
    uses: sublimelsp/workflows/.github/workflows/changed-settings.yaml@v2
    with:
      version_file: 'plugin.py'
      version_regexp: "VSCODE_RELEASE_TAG = '([^']+)'"
